from .AboutUsView import *
from .CadastraAulaView import *
from .IndexView import *
from .LoginView import *
from .LogoutView import *
from .MaisInfoView import *
from .MinhasAulasView import *
from .SalvaAulaView import *
from .SignUpView import *
from .UserPageView import *
from .UsuarioView import *
