from .IndexUrl import *
from .UsuarioUrl import *
from .AboutUsUrl import *
from .LoginUrl import *
from .LogoutUrl import *
from .SignUpUrl import *
from .CadastraAulaUrl import *
from .MaisInfoUrl import *
from .SalvaAulaUrl import *
from .UserPageUrl import *