# Generated by Django 4.2.1 on 2023-09-19 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                ("cod_aula", models.IntegerField(primary_key=True, serialize=False)),
                ("tema_aula", models.CharField(blank=True, max_length=100, null=True)),
                ("desc_aula", models.TextField(blank=True, null=True)),
                ("fluxo_aula", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "info_adicionais",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "Aula",
            },
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "cod_disc",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("nome_disc", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "cod_aula",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_aula",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gerenciaAula.aula",
                    ),
                ),
            ],
            options={
                "db_table": "Disciplina",
            },
        ),
        migrations.CreateModel(
            name="Habilidade",
            fields=[
                (
                    "cod_hab",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("habilidade", models.CharField(blank=True, max_length=60, null=True)),
                ("desc_habilidade", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Habilidade",
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                ("cod_turma", models.IntegerField(primary_key=True, serialize=False)),
                ("nome_turma", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "cod_disc",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_disc",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gerenciaAula.disciplina",
                    ),
                ),
            ],
            options={
                "db_table": "Turma",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "nivel_usuario",
                    models.IntegerField(
                        choices=[(1, "Direçao"), (2, "Coordenação"), (3, "Docente")],
                        default=3,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("eventual_doc", models.BooleanField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "cod_disc",
                    models.ManyToManyField(
                        blank=True,
                        db_column="cod_disc",
                        null=True,
                        to="gerenciaAula.disciplina",
                    ),
                ),
                (
                    "cod_turma",
                    models.ManyToManyField(
                        blank=True,
                        db_column="cod_turma",
                        null=True,
                        to="gerenciaAula.turma",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Usuario",
            },
        ),
        migrations.AddField(
            model_name="aula",
            name="cod_doc",
            field=models.ForeignKey(
                blank=True,
                db_column="id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="gerenciaAula.usuario",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="cod_hab",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_hab",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="gerenciaAula.habilidade",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="cod_turma",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_turma",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="gerenciaAula.turma",
            ),
        ),
    ]
