name: CI/CD - Test and Deploy Django to Fly.io

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
            - name: Install dependencies with Poetry
              run: |
                  poetry install --with dev
            - name: Run tests with pytest
              env:
                  DJANGO_SETTINGS_MODULE: projeto.settings.settings
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
                  DEBUG: ${{ secrets.DEBUG }}
              run: |
                  poetry run pytest

    deploy:
        name: Deploy to Fly.io
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
  
            - name: Install Fly CLI
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy to Fly.io
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              run: flyctl deploy --remote-only
